"""F0 fundacao: acesso, empresa e tabela de apoio

Revision ID: 1f0577e25b9d
Revises:
Create Date: 2026-07-28 23:04:07.892407
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1f0577e25b9d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Toda tabela do VITRA carrega `criado_por_id`. Ver o comentário no fim de upgrade().
TABELAS_COM_AUTOR = (
    "banco",
    "grupo",
    "permissao",
    "uf",
    "cidade",
    "empresa",
    "centro_custo",
    "contador_documento",
    "filial",
    "tabela_apoio",
    "usuario",
    "autorizacao_documento",
)

# Tipos ENUM criados junto com a primeira tabela que os usa; o drop_table não os remove.
ENUMS = ("dominio_apoio", "status_autorizacao", "tipo_autorizacao", "tipo_documento")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banco",
        sa.Column("codigo", sa.String(length=5), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_banco_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_banco")),
        sa.UniqueConstraint("codigo", name=op.f("uq_banco_codigo")),
    )
    op.create_index(op.f("ix_banco_ativo"), "banco", ["ativo"], unique=False)
    op.create_index(op.f("ix_banco_nome"), "banco", ["nome"], unique=False)
    op.create_table(
        "grupo",
        sa.Column("nome", sa.String(length=80), nullable=False),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_grupo_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grupo")),
        sa.UniqueConstraint("nome", name=op.f("uq_grupo_nome")),
    )
    op.create_index(op.f("ix_grupo_ativo"), "grupo", ["ativo"], unique=False)
    op.create_table(
        "permissao",
        sa.Column("recurso", sa.String(length=60), nullable=False),
        sa.Column("acao", sa.String(length=30), nullable=False),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_permissao_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissao")),
        sa.UniqueConstraint("recurso", "acao", name="uq_permissao_recurso_acao"),
    )
    op.create_index(op.f("ix_permissao_recurso"), "permissao", ["recurso"], unique=False)
    op.create_table(
        "uf",
        sa.Column("sigla", sa.String(length=2), nullable=False),
        sa.Column("nome", sa.String(length=60), nullable=False),
        sa.Column("codigo_ibge", sa.String(length=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_uf_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uf")),
        sa.UniqueConstraint("codigo_ibge", name=op.f("uq_uf_codigo_ibge")),
        sa.UniqueConstraint("sigla", name=op.f("uq_uf_sigla")),
    )
    op.create_table(
        "cidade",
        sa.Column("uf_id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("codigo_ibge", sa.String(length=7), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_cidade_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["uf_id"], ["uf.id"], name=op.f("fk_cidade_uf_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cidade")),
        sa.UniqueConstraint("codigo_ibge", name=op.f("uq_cidade_codigo_ibge")),
        sa.UniqueConstraint("uf_id", "nome", name="uq_cidade_uf_nome"),
    )
    op.create_index(op.f("ix_cidade_nome"), "cidade", ["nome"], unique=False)
    op.create_index(op.f("ix_cidade_uf_id"), "cidade", ["uf_id"], unique=False)
    op.create_table(
        "grupo_permissao",
        sa.Column("grupo_id", sa.Uuid(), nullable=False),
        sa.Column("permissao_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grupo_id"], ["grupo.id"], name=op.f("fk_grupo_permissao_grupo_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["permissao_id"],
            ["permissao.id"],
            name=op.f("fk_grupo_permissao_permissao_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("grupo_id", "permissao_id", name=op.f("pk_grupo_permissao")),
    )
    op.create_table(
        "empresa",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("razao_social", sa.String(length=160), nullable=False),
        sa.Column("nome_fantasia", sa.String(length=160), nullable=True),
        sa.Column("cnpj", sa.String(length=18), nullable=True),
        sa.Column("inscricao_estadual", sa.String(length=30), nullable=True),
        sa.Column("inscricao_municipal", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("endereco_cep", sa.String(length=9), nullable=True),
        sa.Column("endereco_logradouro", sa.String(length=160), nullable=True),
        sa.Column("endereco_numero", sa.String(length=20), nullable=True),
        sa.Column("endereco_complemento", sa.String(length=80), nullable=True),
        sa.Column("endereco_bairro", sa.String(length=80), nullable=True),
        sa.Column("endereco_ponto_referencia", sa.String(length=160), nullable=True),
        sa.Column("endereco_cidade_id", sa.Uuid(), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("telefone_secundario", sa.String(length=20), nullable=True),
        sa.Column("celular", sa.String(length=20), nullable=True),
        sa.Column("fax", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("email_secundario", sa.String(length=160), nullable=True),
        sa.Column("site", sa.String(length=160), nullable=True),
        sa.Column("instagram", sa.String(length=120), nullable=True),
        sa.Column("facebook", sa.String(length=120), nullable=True),
        sa.Column("linkedin", sa.String(length=120), nullable=True),
        sa.Column("youtube", sa.String(length=120), nullable=True),
        sa.Column("tiktok", sa.String(length=120), nullable=True),
        sa.Column(
            "comunicadores",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("observacao", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_empresa_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["endereco_cidade_id"],
            ["cidade.id"],
            name=op.f("fk_empresa_endereco_cidade_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_empresa")),
        sa.UniqueConstraint("cnpj", name=op.f("uq_empresa_cnpj")),
        sa.UniqueConstraint("codigo", name=op.f("uq_empresa_codigo")),
    )
    op.create_index(op.f("ix_empresa_ativo"), "empresa", ["ativo"], unique=False)
    op.create_table(
        "centro_custo",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("pai_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("empresa_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_centro_custo_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
            name=op.f("fk_centro_custo_empresa_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pai_id"],
            ["centro_custo.id"],
            name=op.f("fk_centro_custo_pai_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_centro_custo")),
        sa.UniqueConstraint("empresa_id", "codigo", name="uq_centro_custo_empresa_codigo"),
    )
    op.create_index(op.f("ix_centro_custo_ativo"), "centro_custo", ["ativo"], unique=False)
    op.create_index(
        op.f("ix_centro_custo_empresa_id"), "centro_custo", ["empresa_id"], unique=False
    )
    op.create_table(
        "contador_documento",
        sa.Column("empresa_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "orcamento", "pedido_venda", "pedido_compra", "ordem_compra", name="tipo_documento"
            ),
            nullable=False,
        ),
        sa.Column("serie", sa.String(length=10), nullable=False),
        sa.Column("ultimo_numero", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_contador_documento_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
            name=op.f("fk_contador_documento_empresa_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contador_documento")),
        sa.UniqueConstraint("empresa_id", "tipo", "serie", name="uq_contador_empresa_tipo_serie"),
    )
    op.create_table(
        "filial",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("cnpj", sa.String(length=18), nullable=True),
        sa.Column("matriz", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("empresa_id", sa.Uuid(), nullable=False),
        sa.Column("endereco_cep", sa.String(length=9), nullable=True),
        sa.Column("endereco_logradouro", sa.String(length=160), nullable=True),
        sa.Column("endereco_numero", sa.String(length=20), nullable=True),
        sa.Column("endereco_complemento", sa.String(length=80), nullable=True),
        sa.Column("endereco_bairro", sa.String(length=80), nullable=True),
        sa.Column("endereco_ponto_referencia", sa.String(length=160), nullable=True),
        sa.Column("endereco_cidade_id", sa.Uuid(), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("telefone_secundario", sa.String(length=20), nullable=True),
        sa.Column("celular", sa.String(length=20), nullable=True),
        sa.Column("fax", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("email_secundario", sa.String(length=160), nullable=True),
        sa.Column("site", sa.String(length=160), nullable=True),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_filial_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"], ["empresa.id"], name=op.f("fk_filial_empresa_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["endereco_cidade_id"],
            ["cidade.id"],
            name=op.f("fk_filial_endereco_cidade_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filial")),
        sa.UniqueConstraint("empresa_id", "codigo", name="uq_filial_empresa_codigo"),
    )
    op.create_index(op.f("ix_filial_ativo"), "filial", ["ativo"], unique=False)
    op.create_index(op.f("ix_filial_empresa_id"), "filial", ["empresa_id"], unique=False)
    op.create_table(
        "tabela_apoio",
        sa.Column(
            "dominio",
            sa.Enum(
                "setor",
                "grau_instrucao",
                "profissao",
                "raca_cor",
                "estado_civil",
                "nacionalidade",
                "cargo",
                "vinculo",
                "categoria",
                "tipo_produto",
                "tipo_peca",
                "tipo_linha",
                "classificacao",
                "designer_modelo",
                "fabrica",
                "marca",
                "material",
                "unidade",
                "acabamento",
                "tamanho",
                name="dominio_apoio",
            ),
            nullable=False,
        ),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("descricao", sa.String(length=160), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("empresa_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_tabela_apoio_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
            name=op.f("fk_tabela_apoio_empresa_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tabela_apoio")),
        sa.UniqueConstraint("dominio", "codigo", "empresa_id", name="uq_apoio_dominio_codigo_emp"),
    )
    op.create_index(
        "ix_apoio_dominio_descricao", "tabela_apoio", ["dominio", "descricao"], unique=False
    )
    op.create_index(op.f("ix_tabela_apoio_ativo"), "tabela_apoio", ["ativo"], unique=False)
    op.create_index(op.f("ix_tabela_apoio_dominio"), "tabela_apoio", ["dominio"], unique=False)
    op.create_index(
        op.f("ix_tabela_apoio_empresa_id"), "tabela_apoio", ["empresa_id"], unique=False
    )
    op.create_table(
        "usuario",
        sa.Column("login", sa.String(length=60), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column("superusuario", sa.Boolean(), nullable=False),
        sa.Column("limite_desconto_pct", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("empresa_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_usuario_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"], ["empresa.id"], name=op.f("fk_usuario_empresa_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuario")),
    )
    op.create_index(op.f("ix_usuario_ativo"), "usuario", ["ativo"], unique=False)
    op.create_index(op.f("ix_usuario_empresa_id"), "usuario", ["empresa_id"], unique=False)
    op.create_index(op.f("ix_usuario_login"), "usuario", ["login"], unique=True)
    op.create_table(
        "autorizacao_documento",
        sa.Column(
            "documento_tipo",
            sa.Enum(
                "orcamento", "pedido_venda", "pedido_compra", "ordem_compra", name="tipo_documento"
            ),
            nullable=False,
        ),
        sa.Column("documento_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "desconto_acima_do_limite",
                "alteracao_de_preco",
                "liberacao_de_credito",
                name="tipo_autorizacao",
            ),
            nullable=False,
        ),
        sa.Column("solicitante_id", sa.Uuid(), nullable=False),
        sa.Column("autorizador_id", sa.Uuid(), nullable=True),
        sa.Column("valor_solicitado", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pendente", "aprovada", "rejeitada", name="status_autorizacao"),
            nullable=False,
        ),
        sa.Column("motivo", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["autorizador_id"],
            ["usuario.id"],
            name=op.f("fk_autorizacao_documento_autorizador_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["criado_por_id"],
            ["usuario.id"],
            name=op.f("fk_autorizacao_documento_criado_por_id"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["solicitante_id"],
            ["usuario.id"],
            name=op.f("fk_autorizacao_documento_solicitante_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autorizacao_documento")),
    )
    op.create_index(
        op.f("ix_autorizacao_documento_documento_id"),
        "autorizacao_documento",
        ["documento_id"],
        unique=False,
    )
    op.create_table(
        "usuario_grupo",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("grupo_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grupo_id"], ["grupo.id"], name=op.f("fk_usuario_grupo_grupo_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_usuario_grupo_usuario_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("usuario_id", "grupo_id", name=op.f("pk_usuario_grupo")),
    )
    # ### end Alembic commands ###

    # `criado_por_id` referencia `usuario`, que por sua vez depende de `empresa` -> `cidade`
    # -> `uf`: um ciclo. No modelo isso está marcado com `use_alter=True`, mas o
    # `op.create_table` do Alembic descarta essas FKs em silêncio, então elas entram aqui,
    # com todas as tabelas já criadas. Sem este bloco a coluna de auditoria fica sem
    # integridade referencial e o schema migrado diverge do `Base.metadata`.
    for tabela in TABELAS_COM_AUTOR:
        op.create_foreign_key(
            f"fk_{tabela}_criado_por_id",
            tabela,
            "usuario",
            ["criado_por_id"],
            ["id"],
            ondelete="SET NULL",
        )


def downgrade() -> None:
    for tabela in TABELAS_COM_AUTOR:
        op.drop_constraint(f"fk_{tabela}_criado_por_id", tabela, type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usuario_grupo")
    op.drop_index(op.f("ix_autorizacao_documento_documento_id"), table_name="autorizacao_documento")
    op.drop_table("autorizacao_documento")
    op.drop_index(op.f("ix_usuario_login"), table_name="usuario")
    op.drop_index(op.f("ix_usuario_empresa_id"), table_name="usuario")
    op.drop_index(op.f("ix_usuario_ativo"), table_name="usuario")
    op.drop_table("usuario")
    op.drop_index(op.f("ix_tabela_apoio_empresa_id"), table_name="tabela_apoio")
    op.drop_index(op.f("ix_tabela_apoio_dominio"), table_name="tabela_apoio")
    op.drop_index(op.f("ix_tabela_apoio_ativo"), table_name="tabela_apoio")
    op.drop_index("ix_apoio_dominio_descricao", table_name="tabela_apoio")
    op.drop_table("tabela_apoio")
    op.drop_index(op.f("ix_filial_empresa_id"), table_name="filial")
    op.drop_index(op.f("ix_filial_ativo"), table_name="filial")
    op.drop_table("filial")
    op.drop_table("contador_documento")
    op.drop_index(op.f("ix_centro_custo_empresa_id"), table_name="centro_custo")
    op.drop_index(op.f("ix_centro_custo_ativo"), table_name="centro_custo")
    op.drop_table("centro_custo")
    op.drop_index(op.f("ix_empresa_ativo"), table_name="empresa")
    op.drop_table("empresa")
    op.drop_table("grupo_permissao")
    op.drop_index(op.f("ix_cidade_uf_id"), table_name="cidade")
    op.drop_index(op.f("ix_cidade_nome"), table_name="cidade")
    op.drop_table("cidade")
    op.drop_table("uf")
    op.drop_index(op.f("ix_permissao_recurso"), table_name="permissao")
    op.drop_table("permissao")
    op.drop_index(op.f("ix_grupo_ativo"), table_name="grupo")
    op.drop_table("grupo")
    op.drop_index(op.f("ix_banco_nome"), table_name="banco")
    op.drop_index(op.f("ix_banco_ativo"), table_name="banco")
    op.drop_table("banco")
    # ### end Alembic commands ###

    for nome in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {nome}")
