"""fundacao: identidade, empresa, apoio, produtos e auditoria

Revision ID: 24ebf846b5c4
Revises:
Create Date: 2026-07-31 21:00:20.383071
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "24ebf846b5c4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Toda tabela do VITRA carrega `criado_por_id` (`ModeloBase`/`ModeloTenant`). A FK aponta
# para `employees`, que por sua vez tem `criado_por_id` apontando para si mesma — um
# ciclo, marcado com `use_alter=True` no modelo. O `op.create_table` do Alembic **descarta
# essas FKs em silêncio** quando embutidas na criação da tabela: `Table.create()` isolado
# não passa pela resolução de dependência entre tabelas que `MetaData.create_all()` faz, e
# `use_alter=True` nesse caminho só suprime a FK, sem agendar o `ALTER TABLE` que a
# substituiria. Por isso elas entram aqui, à parte, com todas as tabelas já criadas.
TABELAS_COM_AUTOR = (
    "banco",
    "catalog_lookups",
    "employees",
    "grupo",
    "permissao",
    "uf",
    "autorizacao_documento",
    "cidade",
    "tenants",
    "audit_log",
    "centro_custo",
    "contador_documento",
    "filial",
    "products",
    "product_variants",
    "product_tenant",
)

# Tipos ENUM criados junto com a primeira tabela que os usa; o drop_table não os remove.
ENUMS = (
    "dominio_apoio",
    "tipo_documento",
    "tipo_autorizacao",
    "status_autorizacao",
    "acao_auditoria",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banco",
        sa.Column("codigo", sa.String(length=5), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_banco")),
        sa.UniqueConstraint("codigo", name=op.f("uq_banco_codigo")),
    )
    op.create_index(op.f("ix_banco_active"), "banco", ["active"], unique=False)
    op.create_index(op.f("ix_banco_nome"), "banco", ["nome"], unique=False)
    op.create_table(
        "catalog_lookups",
        sa.Column(
            "kind",
            sa.Enum(
                "setor",
                "grau_instrucao",
                "profissao",
                "raca_cor",
                "estado_civil",
                "nacionalidade",
                "cargo",
                "vinculo",
                "categoria",
                "tipo_produto",
                "tipo_peca",
                "tipo_linha",
                "classificacao",
                "designer_modelo",
                "fabrica",
                "marca",
                "material",
                "unidade",
                "acabamento",
                "tamanho",
                name="dominio_apoio",
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_lookups")),
        sa.UniqueConstraint("kind", "code", name="uq_catalog_lookups_kind_code"),
    )
    op.create_index(op.f("ix_catalog_lookups_active"), "catalog_lookups", ["active"], unique=False)
    op.create_index(op.f("ix_catalog_lookups_kind"), "catalog_lookups", ["kind"], unique=False)
    op.create_index(
        "ix_catalog_lookups_kind_name", "catalog_lookups", ["kind", "name"], unique=False
    )
    op.create_table(
        "employees",
        sa.Column("login", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=160), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column("superusuario", sa.Boolean(), nullable=False),
        sa.Column("limite_desconto_pct", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        sa.UniqueConstraint("email", name=op.f("uq_employees_email")),
    )
    op.create_index(op.f("ix_employees_active"), "employees", ["active"], unique=False)
    op.create_index(op.f("ix_employees_login"), "employees", ["login"], unique=True)
    op.create_table(
        "grupo",
        sa.Column("nome", sa.String(length=80), nullable=False),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grupo")),
        sa.UniqueConstraint("nome", name=op.f("uq_grupo_nome")),
    )
    op.create_index(op.f("ix_grupo_active"), "grupo", ["active"], unique=False)
    op.create_table(
        "permissao",
        sa.Column("recurso", sa.String(length=60), nullable=False),
        sa.Column("acao", sa.String(length=30), nullable=False),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissao")),
        sa.UniqueConstraint("recurso", "acao", name="uq_permissao_recurso_acao"),
    )
    op.create_index(op.f("ix_permissao_recurso"), "permissao", ["recurso"], unique=False)
    op.create_table(
        "uf",
        sa.Column("sigla", sa.String(length=2), nullable=False),
        sa.Column("nome", sa.String(length=60), nullable=False),
        sa.Column("codigo_ibge", sa.String(length=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uf")),
        sa.UniqueConstraint("codigo_ibge", name=op.f("uq_uf_codigo_ibge")),
        sa.UniqueConstraint("sigla", name=op.f("uq_uf_sigla")),
    )
    op.create_table(
        "autorizacao_documento",
        sa.Column(
            "documento_tipo",
            sa.Enum(
                "orcamento", "pedido_venda", "pedido_compra", "ordem_compra", name="tipo_documento"
            ),
            nullable=False,
        ),
        sa.Column("documento_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "desconto_acima_do_limite",
                "alteracao_de_preco",
                "liberacao_de_credito",
                name="tipo_autorizacao",
            ),
            nullable=False,
        ),
        sa.Column("solicitante_id", sa.Uuid(), nullable=False),
        sa.Column("autorizador_id", sa.Uuid(), nullable=True),
        sa.Column("valor_solicitado", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pendente", "aprovada", "rejeitada", name="status_autorizacao"),
            nullable=False,
        ),
        sa.Column("motivo", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["autorizador_id"],
            ["employees.id"],
            name=op.f("fk_autorizacao_documento_autorizador_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["solicitante_id"],
            ["employees.id"],
            name=op.f("fk_autorizacao_documento_solicitante_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autorizacao_documento")),
    )
    op.create_index(
        op.f("ix_autorizacao_documento_documento_id"),
        "autorizacao_documento",
        ["documento_id"],
        unique=False,
    )
    op.create_table(
        "cidade",
        sa.Column("uf_id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("codigo_ibge", sa.String(length=7), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uf_id"], ["uf.id"], name=op.f("fk_cidade_uf_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cidade")),
        sa.UniqueConstraint("codigo_ibge", name=op.f("uq_cidade_codigo_ibge")),
        sa.UniqueConstraint("uf_id", "nome", name="uq_cidade_uf_nome"),
    )
    op.create_index(op.f("ix_cidade_nome"), "cidade", ["nome"], unique=False)
    op.create_index(op.f("ix_cidade_uf_id"), "cidade", ["uf_id"], unique=False)
    op.create_table(
        "grupo_permissao",
        sa.Column("grupo_id", sa.Uuid(), nullable=False),
        sa.Column("permissao_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grupo_id"], ["grupo.id"], name=op.f("fk_grupo_permissao_grupo_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["permissao_id"],
            ["permissao.id"],
            name=op.f("fk_grupo_permissao_permissao_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("grupo_id", "permissao_id", name=op.f("pk_grupo_permissao")),
    )
    op.create_table(
        "usuario_grupo",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("grupo_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grupo_id"], ["grupo.id"], name=op.f("fk_usuario_grupo_grupo_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["employees.id"],
            name=op.f("fk_usuario_grupo_usuario_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("usuario_id", "grupo_id", name=op.f("pk_usuario_grupo")),
    )
    op.create_table(
        "tenants",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("razao_social", sa.String(length=160), nullable=False),
        sa.Column("nome_fantasia", sa.String(length=160), nullable=True),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("inscricao_estadual", sa.String(length=30), nullable=True),
        sa.Column("inscricao_municipal", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("endereco_cep", sa.String(length=9), nullable=True),
        sa.Column("endereco_logradouro", sa.String(length=160), nullable=True),
        sa.Column("endereco_numero", sa.String(length=20), nullable=True),
        sa.Column("endereco_complemento", sa.String(length=80), nullable=True),
        sa.Column("endereco_bairro", sa.String(length=80), nullable=True),
        sa.Column("endereco_ponto_referencia", sa.String(length=160), nullable=True),
        sa.Column("endereco_cidade_id", sa.Uuid(), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("telefone_secundario", sa.String(length=20), nullable=True),
        sa.Column("celular", sa.String(length=20), nullable=True),
        sa.Column("fax", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("email_secundario", sa.String(length=160), nullable=True),
        sa.Column("site", sa.String(length=160), nullable=True),
        sa.Column("instagram", sa.String(length=120), nullable=True),
        sa.Column("facebook", sa.String(length=120), nullable=True),
        sa.Column("linkedin", sa.String(length=120), nullable=True),
        sa.Column("youtube", sa.String(length=120), nullable=True),
        sa.Column("tiktok", sa.String(length=120), nullable=True),
        sa.Column(
            "comunicadores",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("observacao", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["endereco_cidade_id"],
            ["cidade.id"],
            name=op.f("fk_tenants_endereco_cidade_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("cnpj", name=op.f("uq_tenants_cnpj")),
        sa.UniqueConstraint("codigo", name=op.f("uq_tenants_codigo")),
    )
    op.create_index(op.f("ix_tenants_active"), "tenants", ["active"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("tabela", sa.String(length=63), nullable=False),
        sa.Column("linha_id", sa.Uuid(), nullable=False),
        sa.Column(
            "acao",
            sa.Enum(
                "criar", "atualizar", "desativar", "reativar", "cancelar", name="acao_auditoria"
            ),
            nullable=False,
        ),
        sa.Column("antes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("depois", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_audit_log_tenant_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_audit_log"),
    )
    op.create_index(
        "ix_audit_log_tenant_tabela_linha",
        "audit_log",
        ["tenant_id", "tabela", "linha_id"],
        unique=False,
    )
    op.create_table(
        "centro_custo",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("pai_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "pai_id"],
            ["centro_custo.tenant_id", "centro_custo.id"],
            name="fk_centro_custo_pai_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_centro_custo_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_centro_custo"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_centro_custo_tenant_codigo"),
    )
    op.create_index(op.f("ix_centro_custo_active"), "centro_custo", ["active"], unique=False)
    op.create_table(
        "contador_documento",
        sa.Column(
            "tipo",
            sa.Enum(
                "orcamento", "pedido_venda", "pedido_compra", "ordem_compra", name="tipo_documento"
            ),
            nullable=False,
        ),
        sa.Column("serie", sa.String(length=10), nullable=False),
        sa.Column("ultimo_numero", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_contador_documento_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_contador_documento"),
        sa.UniqueConstraint("tenant_id", "tipo", "serie", name="uq_contador_tenant_tipo_serie"),
    )
    op.create_table(
        "employee_company",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("grupo_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_company_employee_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["grupo_id"],
            ["grupo.id"],
            name=op.f("fk_employee_company_grupo_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_employee_company_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "employee_id", name="pk_employee_company"),
    )
    op.create_table(
        "filial",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("matriz", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("endereco_cep", sa.String(length=9), nullable=True),
        sa.Column("endereco_logradouro", sa.String(length=160), nullable=True),
        sa.Column("endereco_numero", sa.String(length=20), nullable=True),
        sa.Column("endereco_complemento", sa.String(length=80), nullable=True),
        sa.Column("endereco_bairro", sa.String(length=80), nullable=True),
        sa.Column("endereco_ponto_referencia", sa.String(length=160), nullable=True),
        sa.Column("endereco_cidade_id", sa.Uuid(), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("telefone_secundario", sa.String(length=20), nullable=True),
        sa.Column("celular", sa.String(length=20), nullable=True),
        sa.Column("fax", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("email_secundario", sa.String(length=160), nullable=True),
        sa.Column("site", sa.String(length=160), nullable=True),
        sa.ForeignKeyConstraint(
            ["endereco_cidade_id"],
            ["cidade.id"],
            name=op.f("fk_filial_endereco_cidade_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_filial_tenant_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_filial"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_filial_tenant_codigo"),
    )
    op.create_index(op.f("ix_filial_active"), "filial", ["active"], unique=False)
    op.create_table(
        "products",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_products_tenant_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_products"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_products_tenant_code"),
    )
    op.create_index(op.f("ix_products_active"), "products", ["active"], unique=False)
    op.create_index(
        "ix_products_tenant_description", "products", ["tenant_id", "description"], unique=False
    )
    op.create_table(
        "product_variants",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("finish", sa.String(length=80), nullable=False),
        sa.Column("size", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["products.tenant_id", "products.id"],
            name="fk_product_variants_product",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_product_variants_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_product_variants"),
        sa.UniqueConstraint(
            "tenant_id", "product_id", "finish", "size", name="uq_product_variants_produto"
        ),
    )
    op.create_index(
        op.f("ix_product_variants_active"), "product_variants", ["active"], unique=False
    )
    op.create_table(
        "product_tenant",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("price_cents", sa.BigInteger(), nullable=False),
        sa.Column("stock_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("min_stock", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "price_cents >= 0", name=op.f("ck_product_tenant_price_cents_nao_negativo")
        ),
        sa.CheckConstraint("stock_qty >= 0", name=op.f("ck_product_tenant_stock_qty_nao_negativo")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "variant_id"],
            ["product_variants.tenant_id", "product_variants.id"],
            name="fk_product_tenant_variant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_product_tenant_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_product_tenant"),
        sa.UniqueConstraint("tenant_id", "variant_id", name="uq_product_tenant_variant"),
    )
    # ### end Alembic commands ###

    for tabela in TABELAS_COM_AUTOR:
        op.create_foreign_key(
            f"fk_{tabela}_criado_por_id",
            tabela,
            "employees",
            ["criado_por_id"],
            ["id"],
            ondelete="SET NULL",
        )


def downgrade() -> None:
    for tabela in TABELAS_COM_AUTOR:
        op.drop_constraint(f"fk_{tabela}_criado_por_id", tabela, type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_tenant")
    op.drop_index(op.f("ix_product_variants_active"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index("ix_products_tenant_description", table_name="products")
    op.drop_index(op.f("ix_products_active"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_filial_active"), table_name="filial")
    op.drop_table("filial")
    op.drop_table("employee_company")
    op.drop_table("contador_documento")
    op.drop_index(op.f("ix_centro_custo_active"), table_name="centro_custo")
    op.drop_table("centro_custo")
    op.drop_index("ix_audit_log_tenant_tabela_linha", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_tenants_active"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_table("usuario_grupo")
    op.drop_table("grupo_permissao")
    op.drop_index(op.f("ix_cidade_uf_id"), table_name="cidade")
    op.drop_index(op.f("ix_cidade_nome"), table_name="cidade")
    op.drop_table("cidade")
    op.drop_index(op.f("ix_autorizacao_documento_documento_id"), table_name="autorizacao_documento")
    op.drop_table("autorizacao_documento")
    op.drop_table("uf")
    op.drop_index(op.f("ix_permissao_recurso"), table_name="permissao")
    op.drop_table("permissao")
    op.drop_index(op.f("ix_grupo_active"), table_name="grupo")
    op.drop_table("grupo")
    op.drop_index(op.f("ix_employees_login"), table_name="employees")
    op.drop_index(op.f("ix_employees_active"), table_name="employees")
    op.drop_table("employees")
    op.drop_index("ix_catalog_lookups_kind_name", table_name="catalog_lookups")
    op.drop_index(op.f("ix_catalog_lookups_kind"), table_name="catalog_lookups")
    op.drop_index(op.f("ix_catalog_lookups_active"), table_name="catalog_lookups")
    op.drop_table("catalog_lookups")
    op.drop_index(op.f("ix_banco_nome"), table_name="banco")
    op.drop_index(op.f("ix_banco_active"), table_name="banco")
    op.drop_table("banco")
    # ### end Alembic commands ###

    for nome in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {nome}")
