"""pessoas: cliente, obra, fornecedor, colaborador, profissional externo, transportadora

As sete tabelas nascem já sob RLS, no mesmo molde de `b1c2d3e4f5a6_rls_multiempresa.py`:
`FORCE ROW LEVEL SECURITY` + as quatro políticas sobre o mesmo predicado, `GRANT` de DML
para `vitra_app`. A lista de tabelas é repetida aqui, não importada de `app.models` —
migração é foto do schema num instante do tempo; ver o comentário equivalente na migração
de RLS original.

**Corrigido nesta revisão** (achado ao gerar a migração da S2, autogenerate acusou as sete
FKs de `criado_por_id` como "faltando"): `use_alter=True` num `ForeignKeyConstraint`
passado embutido a `op.create_table()` é **descartado em silêncio** pelo Alembic — esse
sinalizador só tem efeito dentro do ordenador de dependências de
`MetaData.create_all()`, que `op.create_table()` (uma única instrução DDL direta) não
replica. É a mesma pegadinha que a migração `fundacao` já documentava para as 16 tabelas
dela — só que lá as FKs entravam à parte, via `create_foreign_key()` explícito, então
nunca caíram nessa armadilha. Aqui a S1 pôs as sete FKs cedo demais (embutidas no
`create_table()`), e elas nunca chegaram a existir no banco: a coluna `criado_por_id`
existia, a constraint não. Corrigido para o mesmo padrão de `fundacao`.

Revision ID: af281e86c3d5
Revises: b1c2d3e4f5a6
Create Date: 2026-08-01 14:57:54.924043
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "af281e86c3d5"
down_revision: str | None = "b1c2d3e4f5a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABELAS_POR_EMPRESA = (
    "cliente",
    "obra",
    "fornecedor",
    "fornecedor_empresa",
    "colaborador",
    "profissional_externo",
    "transportadora",
)

# As sete têm `criado_por_id` — mesmo papel de `TABELAS_COM_AUTOR` na migração `fundacao`:
# a FK para `employees` entra à parte, depois de todas as tabelas criadas, porque
# `op.create_table()` descarta `use_alter=True` embutido (ver docstring do módulo).
TABELAS_COM_AUTOR = TABELAS_POR_EMPRESA

PAPEL_RUNTIME = "vitra_app"
PREDICADO = "tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"


def _ligar_rls(tabela: str) -> None:
    op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {tabela} FORCE ROW LEVEL SECURITY")
    op.execute(f'CREATE POLICY "{tabela}_sel" ON {tabela} FOR SELECT USING ({PREDICADO})')
    op.execute(f'CREATE POLICY "{tabela}_ins" ON {tabela} FOR INSERT WITH CHECK ({PREDICADO})')
    op.execute(
        f'CREATE POLICY "{tabela}_upd" ON {tabela} FOR UPDATE '
        f"USING ({PREDICADO}) WITH CHECK ({PREDICADO})"
    )
    op.execute(f'CREATE POLICY "{tabela}_del" ON {tabela} FOR DELETE USING ({PREDICADO})')
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {tabela} TO {PAPEL_RUNTIME}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cliente",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("tipo_pessoa", sa.Enum("fisica", "juridica", name="tipo_pessoa"), nullable=False),
        sa.Column("cpf_cnpj", sa.String(length=14), nullable=True),
        sa.Column("rg_ie", sa.String(length=20), nullable=True),
        sa.Column("dt_nascimento", sa.Date(), nullable=True),
        sa.Column("profissao_id", sa.Uuid(), nullable=True),
        sa.Column("estado_civil_id", sa.Uuid(), nullable=True),
        sa.Column("raca_cor_id", sa.Uuid(), nullable=True),
        sa.Column("nacionalidade_id", sa.Uuid(), nullable=True),
        sa.Column("categoria_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("endereco_cep", sa.String(length=9), nullable=True),
        sa.Column("endereco_logradouro", sa.String(length=160), nullable=True),
        sa.Column("endereco_numero", sa.String(length=20), nullable=True),
        sa.Column("endereco_complemento", sa.String(length=80), nullable=True),
        sa.Column("endereco_bairro", sa.String(length=80), nullable=True),
        sa.Column("endereco_ponto_referencia", sa.String(length=160), nullable=True),
        sa.Column("endereco_cidade_id", sa.Uuid(), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("telefone_secundario", sa.String(length=20), nullable=True),
        sa.Column("celular", sa.String(length=20), nullable=True),
        sa.Column("fax", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("email_secundario", sa.String(length=160), nullable=True),
        sa.Column("site", sa.String(length=160), nullable=True),
        sa.Column("observacao", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_cliente_categoria_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["endereco_cidade_id"],
            ["cidade.id"],
            name=op.f("fk_cliente_endereco_cidade_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estado_civil_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_cliente_estado_civil_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["nacionalidade_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_cliente_nacionalidade_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profissao_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_cliente_profissao_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raca_cor_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_cliente_raca_cor_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_cliente_tenant_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_cliente"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_cliente_tenant_codigo"),
    )
    op.create_index(op.f("ix_cliente_active"), "cliente", ["active"], unique=False)
    op.create_index(op.f("ix_cliente_nome"), "cliente", ["nome"], unique=False)
    op.create_table(
        "colaborador",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("dt_admissao", sa.Date(), nullable=True),
        sa.Column("cargo_id", sa.Uuid(), nullable=True),
        sa.Column("setor_id", sa.Uuid(), nullable=True),
        sa.Column("vinculo_id", sa.Uuid(), nullable=True),
        sa.Column("grau_instrucao_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cargo_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_colaborador_cargo_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_colaborador_employee_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["grau_instrucao_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_colaborador_grau_instrucao_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["setor_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_colaborador_setor_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_colaborador_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vinculo_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_colaborador_vinculo_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_colaborador"),
        sa.UniqueConstraint("tenant_id", "employee_id", name="uq_colaborador_tenant_employee"),
    )
    op.create_index(op.f("ix_colaborador_active"), "colaborador", ["active"], unique=False)
    op.create_table(
        "profissional_externo",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("tipo_pessoa", sa.Enum("fisica", "juridica", name="tipo_pessoa"), nullable=False),
        sa.Column("cpf_cnpj", sa.String(length=14), nullable=True),
        sa.Column("profissao_id", sa.Uuid(), nullable=True),
        sa.Column("crea_cau", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("endereco_cep", sa.String(length=9), nullable=True),
        sa.Column("endereco_logradouro", sa.String(length=160), nullable=True),
        sa.Column("endereco_numero", sa.String(length=20), nullable=True),
        sa.Column("endereco_complemento", sa.String(length=80), nullable=True),
        sa.Column("endereco_bairro", sa.String(length=80), nullable=True),
        sa.Column("endereco_ponto_referencia", sa.String(length=160), nullable=True),
        sa.Column("endereco_cidade_id", sa.Uuid(), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("telefone_secundario", sa.String(length=20), nullable=True),
        sa.Column("celular", sa.String(length=20), nullable=True),
        sa.Column("fax", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("email_secundario", sa.String(length=160), nullable=True),
        sa.Column("site", sa.String(length=160), nullable=True),
        sa.ForeignKeyConstraint(
            ["endereco_cidade_id"],
            ["cidade.id"],
            name=op.f("fk_profissional_externo_endereco_cidade_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profissao_id"],
            ["catalog_lookups.id"],
            name=op.f("fk_profissional_externo_profissao_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_profissional_externo_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_profissional_externo"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_profissional_externo_tenant_codigo"),
    )
    op.create_index(
        op.f("ix_profissional_externo_active"), "profissional_externo", ["active"], unique=False
    )
    op.create_index(
        op.f("ix_profissional_externo_nome"), "profissional_externo", ["nome"], unique=False
    )
    op.create_table(
        "transportadora",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("antt", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("endereco_cep", sa.String(length=9), nullable=True),
        sa.Column("endereco_logradouro", sa.String(length=160), nullable=True),
        sa.Column("endereco_numero", sa.String(length=20), nullable=True),
        sa.Column("endereco_complemento", sa.String(length=80), nullable=True),
        sa.Column("endereco_bairro", sa.String(length=80), nullable=True),
        sa.Column("endereco_ponto_referencia", sa.String(length=160), nullable=True),
        sa.Column("endereco_cidade_id", sa.Uuid(), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("telefone_secundario", sa.String(length=20), nullable=True),
        sa.Column("celular", sa.String(length=20), nullable=True),
        sa.Column("fax", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("email_secundario", sa.String(length=160), nullable=True),
        sa.Column("site", sa.String(length=160), nullable=True),
        sa.ForeignKeyConstraint(
            ["endereco_cidade_id"],
            ["cidade.id"],
            name=op.f("fk_transportadora_endereco_cidade_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_transportadora_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_transportadora"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_transportadora_tenant_codigo"),
    )
    op.create_index(op.f("ix_transportadora_active"), "transportadora", ["active"], unique=False)
    op.create_index(op.f("ix_transportadora_nome"), "transportadora", ["nome"], unique=False)
    op.create_table(
        "fornecedor",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("razao_social", sa.String(length=160), nullable=False),
        sa.Column("nome_fantasia", sa.String(length=160), nullable=True),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("transportadora_padrao_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("endereco_cep", sa.String(length=9), nullable=True),
        sa.Column("endereco_logradouro", sa.String(length=160), nullable=True),
        sa.Column("endereco_numero", sa.String(length=20), nullable=True),
        sa.Column("endereco_complemento", sa.String(length=80), nullable=True),
        sa.Column("endereco_bairro", sa.String(length=80), nullable=True),
        sa.Column("endereco_ponto_referencia", sa.String(length=160), nullable=True),
        sa.Column("endereco_cidade_id", sa.Uuid(), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("telefone_secundario", sa.String(length=20), nullable=True),
        sa.Column("celular", sa.String(length=20), nullable=True),
        sa.Column("fax", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("email_secundario", sa.String(length=160), nullable=True),
        sa.Column("site", sa.String(length=160), nullable=True),
        sa.ForeignKeyConstraint(
            ["endereco_cidade_id"],
            ["cidade.id"],
            name=op.f("fk_fornecedor_endereco_cidade_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "transportadora_padrao_id"],
            ["transportadora.tenant_id", "transportadora.id"],
            name="fk_fornecedor_transportadora_padrao",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_fornecedor_tenant_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_fornecedor"),
        sa.UniqueConstraint("tenant_id", "codigo", name="uq_fornecedor_tenant_codigo"),
    )
    op.create_index(op.f("ix_fornecedor_active"), "fornecedor", ["active"], unique=False)
    op.create_index(
        op.f("ix_fornecedor_razao_social"), "fornecedor", ["razao_social"], unique=False
    )
    op.create_table(
        "obra",
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("endereco_cep", sa.String(length=9), nullable=True),
        sa.Column("endereco_logradouro", sa.String(length=160), nullable=True),
        sa.Column("endereco_numero", sa.String(length=20), nullable=True),
        sa.Column("endereco_complemento", sa.String(length=80), nullable=True),
        sa.Column("endereco_bairro", sa.String(length=80), nullable=True),
        sa.Column("endereco_ponto_referencia", sa.String(length=160), nullable=True),
        sa.Column("endereco_cidade_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["endereco_cidade_id"],
            ["cidade.id"],
            name=op.f("fk_obra_endereco_cidade_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "cliente_id"],
            ["cliente.tenant_id", "cliente.id"],
            name="fk_obra_cliente",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_obra_tenant_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_obra"),
    )
    op.create_index(op.f("ix_obra_active"), "obra", ["active"], unique=False)
    op.create_table(
        "fornecedor_empresa",
        sa.Column("fornecedor_id", sa.Uuid(), nullable=False),
        sa.Column("empresa_compradora_id", sa.Uuid(), nullable=False),
        sa.Column("vigencia_inicio", sa.Date(), nullable=False),
        sa.Column("vigencia_fim", sa.Date(), nullable=True),
        sa.Column("motivo", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["empresa_compradora_id"],
            ["tenants.id"],
            name="fk_fornecedor_empresa_compradora",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "fornecedor_id"],
            ["fornecedor.tenant_id", "fornecedor.id"],
            name="fk_fornecedor_empresa_fornecedor",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_fornecedor_empresa_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_fornecedor_empresa"),
    )
    op.create_index(
        "uq_fornecedor_empresa_vigente",
        "fornecedor_empresa",
        ["tenant_id", "fornecedor_id"],
        unique=True,
        postgresql_where=sa.text("vigencia_fim IS NULL"),
    )
    # ### end Alembic commands ###

    for tabela in TABELAS_COM_AUTOR:
        op.create_foreign_key(
            f"fk_{tabela}_criado_por_id",
            tabela,
            "employees",
            ["criado_por_id"],
            ["id"],
            ondelete="SET NULL",
        )

    for tabela in TABELAS_POR_EMPRESA:
        _ligar_rls(tabela)


def downgrade() -> None:
    for tabela in TABELAS_COM_AUTOR:
        op.drop_constraint(f"fk_{tabela}_criado_por_id", tabela, type_="foreignkey")

    for tabela in TABELAS_POR_EMPRESA:
        op.execute(f"ALTER TABLE {tabela} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY")
        for sufixo in ("sel", "ins", "upd", "del"):
            op.execute(f'DROP POLICY IF EXISTS "{tabela}_{sufixo}" ON {tabela}')
        op.execute(f"REVOKE ALL ON {tabela} FROM {PAPEL_RUNTIME}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_fornecedor_empresa_vigente",
        table_name="fornecedor_empresa",
        postgresql_where=sa.text("vigencia_fim IS NULL"),
    )
    op.drop_table("fornecedor_empresa")
    op.drop_index(op.f("ix_obra_active"), table_name="obra")
    op.drop_table("obra")
    op.drop_index(op.f("ix_fornecedor_razao_social"), table_name="fornecedor")
    op.drop_index(op.f("ix_fornecedor_active"), table_name="fornecedor")
    op.drop_table("fornecedor")
    op.drop_index(op.f("ix_transportadora_nome"), table_name="transportadora")
    op.drop_index(op.f("ix_transportadora_active"), table_name="transportadora")
    op.drop_table("transportadora")
    op.drop_index(op.f("ix_profissional_externo_nome"), table_name="profissional_externo")
    op.drop_index(op.f("ix_profissional_externo_active"), table_name="profissional_externo")
    op.drop_table("profissional_externo")
    op.drop_index(op.f("ix_colaborador_active"), table_name="colaborador")
    op.drop_table("colaborador")
    op.drop_index(op.f("ix_cliente_nome"), table_name="cliente")
    op.drop_index(op.f("ix_cliente_active"), table_name="cliente")
    op.drop_table("cliente")
    # ### end Alembic commands ###

    # Tipo ENUM criado junto com a primeira tabela que o usa (`cliente`); `drop_table` não
    # o remove — mesma pegadinha registrada na migração `fundacao`.
    op.execute("DROP TYPE IF EXISTS tipo_pessoa")
