"""produtos: enriquece catalogo, produto_fornecedor, grupos relacionados

`grupo_relacionado`, `item_relacionado` e `produto_fornecedor` nascem já sob RLS, mesma
forma de `af281e86c3d5`/`b1c2d3e4f5a6`: `FORCE ROW LEVEL SECURITY` + as quatro políticas +
`GRANT` de DML para `vitra_app`.

`criado_por_id` das três entra por `create_foreign_key()` explícito, não embutido no
`create_table()` — `use_alter=True` ali é descartado em silêncio pelo Alembic (ver a nota
de correção na migração anterior, `af281e86c3d5`). O autogenerate também acusou as sete FKs
de `criado_por_id` de `cliente`/`obra`/`fornecedor`/`fornecedor_empresa`/`colaborador`/
`profissional_externo`/`transportadora` como "faltando" — eram exatamente as que a correção
em `af281e86c3d5` resolveu; não repetidas aqui, já que agora nascem na migração anterior.

Revision ID: d2cf768cdc65
Revises: af281e86c3d5
Create Date: 2026-08-01 20:15:18.187976
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d2cf768cdc65"
down_revision: str | None = "af281e86c3d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABELAS_POR_EMPRESA = ("grupo_relacionado", "item_relacionado", "produto_fornecedor")

PAPEL_RUNTIME = "vitra_app"
PREDICADO = "tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid"


def _ligar_rls(tabela: str) -> None:
    op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {tabela} FORCE ROW LEVEL SECURITY")
    op.execute(f'CREATE POLICY "{tabela}_sel" ON {tabela} FOR SELECT USING ({PREDICADO})')
    op.execute(f'CREATE POLICY "{tabela}_ins" ON {tabela} FOR INSERT WITH CHECK ({PREDICADO})')
    op.execute(
        f'CREATE POLICY "{tabela}_upd" ON {tabela} FOR UPDATE '
        f"USING ({PREDICADO}) WITH CHECK ({PREDICADO})"
    )
    op.execute(f'CREATE POLICY "{tabela}_del" ON {tabela} FOR DELETE USING ({PREDICADO})')
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {tabela} TO {PAPEL_RUNTIME}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grupo_relacionado",
        sa.Column("produto_id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("padrao", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "produto_id"],
            ["products.tenant_id", "products.id"],
            name="fk_grupo_relacionado_produto",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_grupo_relacionado_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_grupo_relacionado"),
    )
    op.create_index(
        op.f("ix_grupo_relacionado_active"), "grupo_relacionado", ["active"], unique=False
    )
    op.create_table(
        "item_relacionado",
        sa.Column("grupo_id", sa.Uuid(), nullable=False),
        sa.Column("produto_id", sa.Uuid(), nullable=False),
        sa.Column("variante_id", sa.Uuid(), nullable=True),
        sa.Column("quantidade", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("padrao", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "quantidade IS NULL OR quantidade > 0",
            name=op.f("ck_item_relacionado_quantidade_positiva_ou_nula"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "grupo_id"],
            ["grupo_relacionado.tenant_id", "grupo_relacionado.id"],
            name="fk_item_relacionado_grupo",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "produto_id"],
            ["products.tenant_id", "products.id"],
            name="fk_item_relacionado_produto",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "variante_id"],
            ["product_variants.tenant_id", "product_variants.id"],
            name="fk_item_relacionado_variante",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_item_relacionado_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_item_relacionado"),
    )
    op.create_table(
        "produto_fornecedor",
        sa.Column("produto_id", sa.Uuid(), nullable=False),
        sa.Column("fornecedor_id", sa.Uuid(), nullable=False),
        sa.Column("codigo_fornecedor", sa.String(length=60), nullable=True),
        sa.Column("descricao_fornecedor", sa.String(length=300), nullable=True),
        sa.Column("padrao", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("criado_por_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "fornecedor_id"],
            ["fornecedor.tenant_id", "fornecedor.id"],
            name="fk_produto_fornecedor_fornecedor",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "produto_id"],
            ["products.tenant_id", "products.id"],
            name="fk_produto_fornecedor_produto",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_produto_fornecedor_tenant_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_produto_fornecedor"),
        sa.UniqueConstraint(
            "tenant_id", "produto_id", "fornecedor_id", name="uq_produto_fornecedor_par"
        ),
    )
    op.create_index(
        "uq_produto_fornecedor_padrao",
        "produto_fornecedor",
        ["tenant_id", "produto_id"],
        unique=True,
        postgresql_where=sa.text("padrao"),
    )
    op.add_column(
        "product_tenant", sa.Column("indice", sa.Numeric(precision=9, scale=4), nullable=True)
    )
    op.add_column("product_tenant", sa.Column("tipo_valor", sa.String(length=20), nullable=True))
    op.add_column("product_variants", sa.Column("acabamento_id", sa.Uuid(), nullable=False))
    op.add_column("product_variants", sa.Column("tamanho_id", sa.Uuid(), nullable=False))
    op.drop_constraint(op.f("uq_product_variants_produto"), "product_variants", type_="unique")
    op.create_unique_constraint(
        "uq_product_variants_produto",
        "product_variants",
        ["tenant_id", "product_id", "acabamento_id", "tamanho_id"],
    )
    op.create_foreign_key(
        op.f("fk_product_variants_tamanho_id"),
        "product_variants",
        "catalog_lookups",
        ["tamanho_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_product_variants_acabamento_id"),
        "product_variants",
        "catalog_lookups",
        ["acabamento_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("product_variants", "size")
    op.drop_column("product_variants", "finish")
    op.add_column("products", sa.Column("codigo_especial", sa.String(length=40), nullable=True))
    op.add_column("products", sa.Column("codigo_reduzido", sa.String(length=20), nullable=True))
    op.add_column(
        "products", sa.Column("descricao_complementar", sa.String(length=500), nullable=True)
    )
    op.add_column("products", sa.Column("dt_vigencia", sa.Date(), nullable=True))
    op.add_column("products", sa.Column("tipo_produto_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("tipo_peca_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("tipo_linha_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("classificacao_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("designer_modelo_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("fabrica_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("marca_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("unidade_entrada_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("unidade_saida_id", sa.Uuid(), nullable=True))
    op.add_column(
        "products", sa.Column("qtd_entrada", sa.Numeric(precision=14, scale=3), nullable=False)
    )
    op.add_column(
        "products", sa.Column("qtd_saida", sa.Numeric(precision=14, scale=3), nullable=False)
    )
    op.add_column("products", sa.Column("empresa_compradora_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("fora_de_linha", sa.Boolean(), nullable=False))
    op.add_column("products", sa.Column("consultar_valor", sa.Boolean(), nullable=False))
    op.add_column("products", sa.Column("sobre_medida", sa.Boolean(), nullable=False))
    op.add_column("products", sa.Column("publicar_no_site", sa.Boolean(), nullable=False))
    op.add_column("products", sa.Column("ncm", sa.String(length=8), nullable=True))
    op.add_column("products", sa.Column("cest", sa.String(length=7), nullable=True))
    op.add_column("products", sa.Column("origem", sa.String(length=1), nullable=True))
    op.add_column(
        "products",
        sa.Column(
            "especificacao",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("fk_products_classificacao_id"),
        "products",
        "catalog_lookups",
        ["classificacao_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_products_unidade_entrada_id"),
        "products",
        "catalog_lookups",
        ["unidade_entrada_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_products_designer_modelo_id"),
        "products",
        "catalog_lookups",
        ["designer_modelo_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_products_empresa_compradora_id"),
        "products",
        "tenants",
        ["empresa_compradora_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_products_fabrica_id"),
        "products",
        "catalog_lookups",
        ["fabrica_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_products_unidade_saida_id"),
        "products",
        "catalog_lookups",
        ["unidade_saida_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_products_marca_id"),
        "products",
        "catalog_lookups",
        ["marca_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_products_tipo_linha_id"),
        "products",
        "catalog_lookups",
        ["tipo_linha_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_products_tipo_peca_id"),
        "products",
        "catalog_lookups",
        ["tipo_peca_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_products_tipo_produto_id"),
        "products",
        "catalog_lookups",
        ["tipo_produto_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###

    for tabela in TABELAS_POR_EMPRESA:
        op.create_foreign_key(
            f"fk_{tabela}_criado_por_id",
            tabela,
            "employees",
            ["criado_por_id"],
            ["id"],
            ondelete="SET NULL",
        )

    for tabela in TABELAS_POR_EMPRESA:
        _ligar_rls(tabela)


def downgrade() -> None:
    for tabela in TABELAS_POR_EMPRESA:
        op.execute(f"ALTER TABLE {tabela} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY")
        for sufixo in ("sel", "ins", "upd", "del"):
            op.execute(f'DROP POLICY IF EXISTS "{tabela}_{sufixo}" ON {tabela}')
        op.execute(f"REVOKE ALL ON {tabela} FROM {PAPEL_RUNTIME}")

    for tabela in TABELAS_POR_EMPRESA:
        op.drop_constraint(f"fk_{tabela}_criado_por_id", tabela, type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_products_tipo_produto_id"), "products", type_="foreignkey")
    op.drop_constraint(op.f("fk_products_tipo_peca_id"), "products", type_="foreignkey")
    op.drop_constraint(op.f("fk_products_tipo_linha_id"), "products", type_="foreignkey")
    op.drop_constraint(op.f("fk_products_marca_id"), "products", type_="foreignkey")
    op.drop_constraint(op.f("fk_products_unidade_saida_id"), "products", type_="foreignkey")
    op.drop_constraint(op.f("fk_products_fabrica_id"), "products", type_="foreignkey")
    op.drop_constraint(op.f("fk_products_empresa_compradora_id"), "products", type_="foreignkey")
    op.drop_constraint(op.f("fk_products_designer_modelo_id"), "products", type_="foreignkey")
    op.drop_constraint(op.f("fk_products_unidade_entrada_id"), "products", type_="foreignkey")
    op.drop_constraint(op.f("fk_products_classificacao_id"), "products", type_="foreignkey")
    op.drop_column("products", "especificacao")
    op.drop_column("products", "origem")
    op.drop_column("products", "cest")
    op.drop_column("products", "ncm")
    op.drop_column("products", "publicar_no_site")
    op.drop_column("products", "sobre_medida")
    op.drop_column("products", "consultar_valor")
    op.drop_column("products", "fora_de_linha")
    op.drop_column("products", "empresa_compradora_id")
    op.drop_column("products", "qtd_saida")
    op.drop_column("products", "qtd_entrada")
    op.drop_column("products", "unidade_saida_id")
    op.drop_column("products", "unidade_entrada_id")
    op.drop_column("products", "marca_id")
    op.drop_column("products", "fabrica_id")
    op.drop_column("products", "designer_modelo_id")
    op.drop_column("products", "classificacao_id")
    op.drop_column("products", "tipo_linha_id")
    op.drop_column("products", "tipo_peca_id")
    op.drop_column("products", "tipo_produto_id")
    op.drop_column("products", "dt_vigencia")
    op.drop_column("products", "descricao_complementar")
    op.drop_column("products", "codigo_reduzido")
    op.drop_column("products", "codigo_especial")
    op.add_column(
        "product_variants",
        sa.Column("finish", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    )
    op.add_column(
        "product_variants",
        sa.Column("size", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_product_variants_acabamento_id"), "product_variants", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_product_variants_tamanho_id"), "product_variants", type_="foreignkey"
    )
    op.drop_constraint("uq_product_variants_produto", "product_variants", type_="unique")
    op.create_unique_constraint(
        op.f("uq_product_variants_produto"),
        "product_variants",
        ["tenant_id", "product_id", "finish", "size"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("product_variants", "tamanho_id")
    op.drop_column("product_variants", "acabamento_id")
    op.drop_column("product_tenant", "tipo_valor")
    op.drop_column("product_tenant", "indice")
    op.drop_index(
        "uq_produto_fornecedor_padrao",
        table_name="produto_fornecedor",
        postgresql_where=sa.text("padrao"),
    )
    op.drop_table("produto_fornecedor")
    op.drop_table("item_relacionado")
    op.drop_index(op.f("ix_grupo_relacionado_active"), table_name="grupo_relacionado")
    op.drop_table("grupo_relacionado")
    # ### end Alembic commands ###
